# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arcjet < Formula
  desc "Arcjet CLI — manage Arcjet from the terminal"
  homepage "https://arcjet.com"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arcjet/cli/releases/download/v0.5.2/arcjet_0.5.2_darwin_amd64.tar.gz"
      sha256 "d39e4f2f201482b1423eeb22b2731fe8189429e6e4ddd005b3f5c8c2f01b227c"

      define_method(:install) do
        bin.install "arcjet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arcjet/cli/releases/download/v0.5.2/arcjet_0.5.2_darwin_arm64.tar.gz"
      sha256 "806cc0dc873ecc1bca573eff464d2cd14c9a3dbbb09ef63365554a22c4f0bd48"

      define_method(:install) do
        bin.install "arcjet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcjet/cli/releases/download/v0.5.2/arcjet_0.5.2_linux_amd64.tar.gz"
      sha256 "2d27eeaa3d918b14989899d038ae0d67827e58e410921a4394540c2b2df13e17"
      define_method(:install) do
        bin.install "arcjet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcjet/cli/releases/download/v0.5.2/arcjet_0.5.2_linux_arm64.tar.gz"
      sha256 "a77cb667558d9fffb63275ff5126851277ee9156d89c92fc07cc70b7c467016e"
      define_method(:install) do
        bin.install "arcjet"
      end
    end
  end

  test do
    system "#{bin}/arcjet", "version"
  end
end
