# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arcjet < Formula
  desc "Arcjet CLI — manage Arcjet from the terminal"
  homepage "https://arcjet.com"
  version "0.5.1-test"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arcjet/cli/releases/download/v0.5.1-test/arcjet_0.5.1-test_darwin_amd64.tar.gz"
      sha256 "1617ef75638768296bd2d5e258c57e2eb30d03447736a21b522326e17506fdc4"

      define_method(:install) do
        bin.install "arcjet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arcjet/cli/releases/download/v0.5.1-test/arcjet_0.5.1-test_darwin_arm64.tar.gz"
      sha256 "7f89241b52f56a2d2a15716743d386363423688efa958e135938e39157062af5"

      define_method(:install) do
        bin.install "arcjet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcjet/cli/releases/download/v0.5.1-test/arcjet_0.5.1-test_linux_amd64.tar.gz"
      sha256 "bce7b491becbfecd28afea091b07261b53c4cef98e6a2016be1d0237f9f2e2c2"
      define_method(:install) do
        bin.install "arcjet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcjet/cli/releases/download/v0.5.1-test/arcjet_0.5.1-test_linux_arm64.tar.gz"
      sha256 "b8074cbd45f12367cc4ad0934a7af0b86d481850a0853e24c62c03092fe49fbe"
      define_method(:install) do
        bin.install "arcjet"
      end
    end
  end

  test do
    system "#{bin}/arcjet", "version"
  end
end
