# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arcjet < Formula
  desc "Arcjet CLI — manage Arcjet from the terminal"
  homepage "https://arcjet.com"
  version "0.5.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arcjet/cli/releases/download/v0.5.4/arcjet_0.5.4_darwin_amd64.tar.gz"
      sha256 "744d94e4f182706dee36e5440cfec45611f6273ad5c6725d3a507200b2bf1245"

      define_method(:install) do
        bin.install "arcjet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arcjet/cli/releases/download/v0.5.4/arcjet_0.5.4_darwin_arm64.tar.gz"
      sha256 "56ebd7361e9a5f16e6bbe8279cfbe0e07dc17ed6d6c65f6ecfcceda4c631d2d4"

      define_method(:install) do
        bin.install "arcjet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcjet/cli/releases/download/v0.5.4/arcjet_0.5.4_linux_amd64.tar.gz"
      sha256 "e64e33a03cd3712bfe6ee8b3ef408d005cb02850e9a3f5bf385983021e3910be"
      define_method(:install) do
        bin.install "arcjet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arcjet/cli/releases/download/v0.5.4/arcjet_0.5.4_linux_arm64.tar.gz"
      sha256 "6abdaa79b10ea12df3f346a8c367932ee6e3400d69ef44e12b5f2d21fe17f967"
      define_method(:install) do
        bin.install "arcjet"
      end
    end
  end

  test do
    system "#{bin}/arcjet", "version"
  end
end
